
export const CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_CONTRACT_ADDRESS || "SP2ZNGJ85ENDY6QRHQ5P2D4UX57X5CZH9W9P1V4QE";
export const CONTRACT_NAME = process.env.NEXT_PUBLIC_CONTRACT_NAME || "tippy";

export const getContractIdentifier = () => `${CONTRACT_ADDRESS}.${CONTRACT_NAME}`;
